### ISSUE TITLE
bug: `reference_script` semicolon misplaced

### ISSUE THREAD

**Issue by burgeon-env** [RinteRface/charpente#17]
Thanks for all the work done, it is really awesome!

There is a little (but important) misspelling in the `reference_script` function, at line 121 of `utils.R`, where the semicolon is placed inside the file name and that lets to an `error: Could not resolve "./<name>;"` from `esbuild`.

The problem is at `sprintf("import './%s.js;'", name)`

Whole function code should look like this (although semicolon could be avoided since I've test it and newline does the work, IMHO it is better if it stays there):
```R
reference_script <- function(name) {
  write(
    sprintf("import './%s.js';", name),
    file = "./srcjs/main.js",
    append = TRUE
  )
  ui_done("Script successfully added to JS entry point!")
}

```

**Comment by DivadNojnarg** [comment]
Great thx. This is bad. I'll fix it.
